class Config:
    def __init__(self, MONGODB_URI, JWT_ALGORITHM, JWT_SECRET, JWT_PUBLIC_KEY_PATH, JWT_PRIVATE_KEY_PATH, LIMITER_STORAGE_URL, LIMITER_STRATEGY, COMPANY_NAME, COMPANY_WEBSITE, SMTP_SERVER, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, SMTP_EMAILSENDER):
        self.MONGODB_URI = MONGODB_URI
        self.JWT_ALGORITHM = JWT_ALGORITHM or 'HS256'
        self.JWT_SECRET = JWT_SECRET
        self.JWT_PUBLIC_KEY_PATH = JWT_PUBLIC_KEY_PATH
        self.JWT_PRIVATE_KEY_PATH = JWT_PRIVATE_KEY_PATH
        self.LIMITER_STORAGE_URL = LIMITER_STORAGE_URL
        self.LIMITER_STRATEGY = LIMITER_STRATEGY or "fixed-window"
        self.COMPANY_NAME = COMPANY_NAME
        self.COMPANY_WEBSITE = COMPANY_WEBSITE
        self.SMTP_SERVER = SMTP_SERVER
        self.SMTP_PORT = SMTP_PORT
        self.SMTP_USER = SMTP_USER
        self.SMTP_PASSWORD = SMTP_PASSWORD
        self.SMTP_EMAILSENDER = SMTP_EMAILSENDER